[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "python3 -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "python app.py"
